### PR TITLE
Feat: add sx utility for conditional styles

### PR DESCRIPTION
**Pull request by everton0991**
image
image

### CODE REVIEW

**Review by adrianbona — APPROVED** [review]
Nice work

**Comment by adrianbona** [comment]
@everton0991 can we have a screenshot added of how the result looks like?

**Comment by everton0991** [comment]
> @everton0991 can we have a screenshot added of how the result looks like?

Done!

**Comment by adrianbona** [comment]
@everton0991 thanks for the update! Remember that you need to update the theme to override the text transformation since MUI shows the button's text using uppercase by default. [You can see more here!](https://github.com/alicenet/alice-mui-provider/blob/83f13c28fff18c2ab68723467d84a1f18c01158a/src/style/theme.js#L50)

**Comment by adrianbona** [comment]
Also, the active color for the input might need to be updated to match the secondary color instead of the primary. Just some details, it looks great.

**Comment by everton0991** [comment]
@adrianbona 
image

**Comment by adrianbona** [comment]
Awesome! Remember that later we are gonna start consuming the theme and importing it from [here](https://github.com/alicenet/alice-mui-provider/blob/83f13c28fff18c2ab68723467d84a1f18c01158a/src/style/theme.js) which is gonna make it easier for us to share all the styling across the different repos.

> @adrianbona image

Looks awesome! Remember that later we are gonna start consuming the theme and importing it from [here](https://github.com/alicenet/alice-mui-provider/blob/83f13c28fff18c2ab68723467d84a1f18c01158a/src/style/theme.js) which is gonna make it easier for us to share all the styling across the different repos.

**Pull request merged**
